name: Repository Creation

on:
  repository:
    types: [created]

jobs:
  add-team-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add team as admin
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/${{ github.repository }}/collaborators/teams/id-team
          token: ${{ secrets.GITHUB_TOKEN }}
          permissions: admin
